// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import DropdownComponentController from '../../components/dropdown_component/dropdown_component_controller';
import FlashComponentController from '../../components/flash_component/flash_component_controller';
import CanvasController from './canvas_controller';
import TableTbodyController from './table_tbody_controller';
import FocusController from './focus_controller';
import RedirectController from './redirect_controller';
import DragController from './drag_controller';

import AnnotationController from './annotation_controller';
import AnnotationsToggleButtonsController from './annotations/toggle_buttons_controller';
import AnnotationsQueryFormController from './annotations/query_form_controller';
import FoodNutrientsFormController from './food_nutrients/form_controller';

import QueryFormController from './query_form_controller';

import AnnotationItemsFormController from './annotation_items/form_controller';
import AnnotationItemsSelectController from './annotation_items/select_controller';

import FoodsSelectController from './foods/select_controller';

import FoodListsSelectController from './food_lists/select_controller';

import FoodSetsSelectController from './food_sets/select_controller';

// Webauthn
import WebauthnRegisterController from './webauthn/register_controller';
import WebauthnAuthenticationController from './webauthn/authentication_controller';

// Collab layout
import SidebarComponentController
  from '../../components/collab/sidebar_component/sidebar_component_controller';
import MobileSidebarButtonComponentController
  from '../../components/collab/mobile_sidebar_button_component/mobile_sidebar_button_component_controller';
import BottomNavComponentController
  from '../../components/collab/sidebar_component/bottom_nav_component_controller';
import CommentFormComponentController
  from '../../components/collab/annotations/comment_form_component/comment_form_component_controller';

application.register('dropdown-component', DropdownComponentController);
application.register('flash-component', FlashComponentController);
application.register('canvas', CanvasController);
application.register('table-tbody', TableTbodyController);
application.register('focus', FocusController);
application.register('redirect', RedirectController);
application.register('drag', DragController);

application.register('annotation', AnnotationController);
application.register('annotations--toggle-buttons', AnnotationsToggleButtonsController);
application.register('annotations--query-form', AnnotationsQueryFormController);
application.register('food-nutrients--form', FoodNutrientsFormController);

application.register('query-form', QueryFormController);

application.register('annotation-items--form', AnnotationItemsFormController);
application.register('annotation-items--select', AnnotationItemsSelectController);

application.register('foods--select', FoodsSelectController);

application.register('food-lists--select', FoodListsSelectController);

application.register('food-sets--select', FoodSetsSelectController);

// Webauthn
application.register('webauthn--register', WebauthnRegisterController);
application.register('webauthn--authentication', WebauthnAuthenticationController);

// Collab layout
application.register('sidebar-component', SidebarComponentController);
application.register('mobile-sidebar-button-component', MobileSidebarButtonComponentController);
application.register('bottom-nav-component', BottomNavComponentController);
application.register('comment-form', CommentFormComponentController);
