FROM ruby:3.2.2-alpine
LABEL mainainer="dev@myfoodrepo.org"
LABEL org.opencontainers.image.source="https://github.com/digitalepidemiologylab/myfoodrepo"

RUN apk add --no-cache --update build-base \
  bash \
  git \
  postgresql-dev \
  nodejs \
  yarn \
  vips \
  tzdata \
  gcompat \
  vim \
  graphviz \
  font-noto \
  fontconfig \
  && rm -rf /var/cache/apk/*

RUN fc-cache -f

WORKDIR /app

RUN echo 'gem: --no-rdoc --no-ri >> "$HOME/.gemrc"'

ENV PATH ./bin:$PATH

COPY Gemfile Gemfile.lock package.json yarn.lock ./

RUN gem update --system
RUN bundle config set --local force_ruby_platform true
RUN bundle install -j $(nproc)
RUN yarn install --frozen-lockfile --non-interactive

ENTRYPOINT ["./docker/docker-entrypoint.sh"]
