global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedbydefault: false

  file:
    filename: /etc/traefik/tls.yml
    watch: true

log:
  level: ERROR
  format: common

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  https:
    address: ':443'

  capybara-0:
    address: ':4000'

  capybara-1:
    address: ':4001'

  capybara-2:
    address: ':4002'

  capybara-3:
    address: ':4003'

  capybara-4:
    address: ':4004'

  capybara-5:
    address: ':4005'

  capybara-6:
    address: ':4006'

  capybara-7:
    address: ':4007'

  capybara-8:
    address: ':4008'

  capybara-9:
    address: ':4009'

  capybara-10:
    address: ':4010'

  capybara-11:
    address: ':4011'

  capybara-12:
    address: ':4012'
